CMS_HOST: studio.learn.quasar-university.org
CMS_OAUTH2_SECRET: ODGDfCvD3qFGC2bpleccks60
CONTACT_EMAIL: support@quasar-university.org
ENABLE_HTTPS: true
ID: 1XItMqUzc5gMDZHsPprJ9cQG
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEogIBAAKCAQEA1D7lPZ212NOs25z7rmL6PG4C6HlrlRcOMWZc2tEGCeAG43jx

  VtrXoJoO9Dl/w5ROnlv6VE+2KwZDcwDbjTSA9Zb/Xf6EuMWrIffxCpAyLft61nV8

  PH2z5e8Wr+O0vw+2ngu8rj2nqwMg4pIUH8jJou42GO1mU9CPHn2/Zgqw6ZgU7sLy

  FN8W8/ITFaElG0nCPt67RSj7FBCkVAbR64IqoBCGtd7pscuN94n39jzXel/B0Dmw

  CA0ck/d6aQkMOYznnmNXynASnJHEHRrq6fDO2q7H0Syw5VRnf0yqh7HTlemS6ZYl

  tJb8tVuKU8/U6nb//PT0ZW3tsDKoePbf9yW/dQIDAQABAoIBAFV3NixHk3BKXHLa

  leY06ProebdPHWkdrZNq2r0qKjpTwbJbgyMsYGPFZXwmozIISFgwRW8p4fsVPJfU

  opQLrlo2gYJB+QPGZRD6nE9anToy59Xv3SUmoQhX7FTLZn8BPtIJe+LV5OxSCC30

  ELJz0e4P6izDe88ITnlCvY3DhFWrMhQKn3Jo717QMrwXlX3z94pK9xR2JMlbPPa+

  HKfiYm7fOvVDYE9CJ4GqMMCyJx9Z1VvkHaOZZTnUJnTrhauFYIqYzKghuJZgHJR2

  n0AEUJdgzXQeAkjDU7QTk04EPbFk4FpPpLfqz4tPsp7LDLbEVhV3U4f9r4Q27mlO

  XuZ8nAkCgYEA5gJLXYRW7ZI0zEXDRf3F5o0LKBTWCXF9ufp9R2FHjzyY9q98tUWp

  FGdsRYTdCJhvk95tVl56FnLisJlAxSGjABrlclsOMwzYh7vM8w35vJZd/AOwF1xZ

  MaVgcCNXWvhFL+K3pPIZTsYzvJfsA/A3myJftHHWDzFDyCehFtYfZ/MCgYEA7Dq+

  mBDx/3BLZTr6ZT2rErbTvHry6jCXUQCNcli55VCN1kC4VMwH3kbcE+z9j9BU+09R

  Styq0kH48dh0dVr5Sfm10Wdnm+12vQZDFjxG/67zcszQGVfhYfm/dLdbRPkdGqYE

  mNxCqnrGRicpr2VLM3q/Eb6JztcHrzXzyan2vPcCgYBZhBcUxEaYm0hVH+mJueRl

  gAsRhFpwvmyyDtznBOM2ydy2VUHxwrS1LjMjMzxa9gimwfBHpulZB0lWda6Rii/I

  AK+/u9Rg5eT3no17IrtJPDRDuqOz08sa2UQZIIgE7Y7vvgq+9UIIOHc2NOIz/i+F

  /vDEZ3Fp5EB/C31UR+1dJQKBgDaosQkGgrgUB534s49RYZAG9Z8a47IEZD693fyj

  QwAoT2lPuFcGjpuD0dBaeaEZF1C+3ZRw0qWr1io/Z1LwJdZUDRnSz0po+5xpIoS2

  lcb7eCEL+uqiRuggnYgoFNo0ueM8nruv200O82mwDhkjWu8ia6tzZveREZoc5be3

  t/upAoGALr7zmAEjC/X5Zq3R4wDel0lwWzLgO1+CsouKmMoPX3SMXqFC+SeROHHd

  0N5LQji8JquTD4fsRyqqj2F7a+1H9mEWUwS6Zrw8Vn5LNxh5/C4pOVdJBexLmKX3

  ZKhwkzRuWRYIDyUioRA7G7jn/87Gn2nZq02B43JFrDrLXV2VjS4=

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: learn.quasar-university.org
MEILISEARCH_API_KEY: 86ebfa84dfab27a44c4ec2f4e0f43e1475e907dfbaf75d14872e9a53c157c604
MEILISEARCH_API_KEY_UID: 235fa9c7-1db7-4a2f-b2be-3d0350ab7ff8
MEILISEARCH_MASTER_KEY: oKpUXAvR331SKgiD6lzg77z6
MYSQL_ROOT_PASSWORD: QwFGd6OJ
OPENEDX_MYSQL_PASSWORD: FhZk7ZRp
OPENEDX_SECRET_KEY: UH1hdVlPpFrGBqZPkdGMugNq
PLATFORM_NAME: Quasar Academy
PLUGINS:
- forum
- indigo
- mfe
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
- https://overhang.io/tutor/contrib
